DEFAULT_PROVIDER_DEFINITIONS = (
    {
        "code": "ryanair",
        "name": "Ryanair",
        "adapter_path": "apps.providers.adapters.ryanair.RyanairAdapter",
        "website_url": "https://www.ryanair.com/",
        "config_json": {
            "base_url": "https://www.ryanair.com/api/farfnd/v4",
            "market": "en-gb",
            "language": "en",
            "timeout": 30.0,
            "max_price": 1000,
            "cooldown_minutes": 5,
            "fare_identity_keys": [
                "outbound.flightKey",
                "outbound.departureDate",
            ],
        },
        "is_active": True,
    },
    {
        "code": "wizzair",
        "name": "Wizz Air",
        "adapter_path": "apps.providers.adapters.wizzair.WizzAirAdapter",
        "website_url": "https://wizzair.com/",
        "config_json": {
            "base_url": "https://be.wizzair.com/9.13.0/Api",
            "market": "en-gb",
            "timeout": 30.0,
            "cooldown_minutes": 30,
            "rate_limit_cooldown_minutes": 90,
            "bootstrap_enabled": True,
            "cookie_header": "",
            "playwright_fallback_enabled": True,
            "playwright_headless": True,
            "playwright_timeout_ms": 45000,
            "fare_identity_keys": [
                "flightNumber",
                "departureDate",
                "departureDateTime",
            ],
        },
        "is_active": True,
    },
)
